# Generated by Django 3.2.3 on 2021-09-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
