# Generated by Django 3.2.3 on 2021-09-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('startDate', models.DateTimeField(verbose_name='date')),
                ('amount', models.FloatField(verbose_name='amount')),
            ],
        ),
    ]
