# Generated by Django 3.2.3 on 2021-09-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablei',
            name='amount',
            field=models.FloatField(verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='tablei',
            name='startDate',
            field=models.DateTimeField(verbose_name='birth'),
        ),
    ]
