# Generated by Django 3.2.3 on 2021-09-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module', '0003_auto_20210914_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablei',
            name='birth',
            field=models.DateField(verbose_name='birth'),
        ),
    ]
